-- 법령 조문 본문 적재 + 조문 검색 RPC (2026-10-05)
--
-- 왜. 챗봇이 모으던 것은 FAQ · 노동위 판정례 · 행정해석 · 법원 판례 · 뉴스였다.
-- 전부 간접 자료이고 **법령 조문이 없었다.** `law_articles` 441행은 `exists_flag` 와
-- 제목만 있고 본문이 없었다(2026-04-25 이후 멈춤, 법령명에 「테스트」도 섞여 있었다).
-- `src/lib/legal-verify.ts` 주석에 「장기적으론 법제처 API에서 13개 주요 법령 backfill
-- 필요」로 남아 있던 것을 했다.
--
-- 적재는 서버2 스크립트가 한다 (레포 밖):
--   work-orchestrator/scripts/fetch_law_articles.py --from-site   수집
--   work-orchestrator/scripts/load_law_articles.py --apply        적재
-- 결과: 93종 7,887행 · 본문 982만자 · 조문 6,858 · 별표·서식 1,029 · 삭제조문 284

-- ── 1. 컬럼 추가. 기존 컬럼은 건드리지 않는다(기존 코드 호환) ──
ALTER TABLE law_articles
  ADD COLUMN IF NOT EXISTS article_label text,
  ADD COLUMN IF NOT EXISTS sub_number int,
  ADD COLUMN IF NOT EXISTS article_title text,
  ADD COLUMN IF NOT EXISTS body text,
  ADD COLUMN IF NOT EXISTS law_kind text,
  ADD COLUMN IF NOT EXISTS law_mst text,
  ADD COLUMN IF NOT EXISTS effective_date date,
  ADD COLUMN IF NOT EXISTS article_effective_date date,
  ADD COLUMN IF NOT EXISTS is_heading boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_deleted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_byeolpyo boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS ordinal int;

-- ── 2. PK 변경 ──
-- (law_name, article_number) 가 유일하지 않다:
--   · 제105조 와 제105조의2 가 둘 다 article_number = 105
--   · 별표 1 과 제1조가 둘 다 1
--   · 장·절 표제가 조문과 같은 번호를 쓴다
-- 2행 이상인 조합 1,584건(해당 4,456행) 실측. 어떤 자연키도 유일하지 않다 —
-- 법령 조문은 **순서가 의미**여서 id + ordinal(법령 내 등장 순서)로 간다.
ALTER TABLE law_articles DROP CONSTRAINT IF EXISTS law_articles_pkey;
ALTER TABLE law_articles ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE law_articles SET ordinal = 0 WHERE ordinal IS NULL;
ALTER TABLE law_articles ADD PRIMARY KEY (id);

-- ⚠ 되돌리려면 아래. 단 가지번호·별표가 적재된 상태에서는 중복으로 실패한다.
--   ALTER TABLE law_articles DROP CONSTRAINT law_articles_pkey;
--   ALTER TABLE law_articles ADD PRIMARY KEY (law_name, article_number);

-- ── 3. 인덱스 ──
CREATE INDEX IF NOT EXISTS law_articles_name_label_idx ON law_articles (law_name, article_label);
CREATE INDEX IF NOT EXISTS law_articles_name_num_idx   ON law_articles (law_name, article_number);
CREATE INDEX IF NOT EXISTS law_articles_ord_idx        ON law_articles (law_name, ordinal);
CREATE INDEX IF NOT EXISTS law_articles_title_trgm_idx ON law_articles USING gin (article_title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS law_articles_body_trgm_idx  ON law_articles USING gin (body gin_trgm_ops);

-- ── 4. 조문 검색 RPC ──
-- 어휘 기반이다. **임베딩을 쓰지 않는다** — 그래서 임베딩 생성이 실패한 요청에서도
-- 1차 자료가 들어간다. 후보를 넓게 내고 고르기는 Jev(LLM 재선택)에 맡긴다.
--
-- 질의를 토큰으로 쪼개 점수를 합산한다. 챗봇 질문은 문장이라 전체 구로 ILIKE 하면
-- 거의 0건이 된다(「직장 내 괴롭힘 조사」로 3건). 앱이 lex-query.ts 로 내용어만
-- 뽑아 넘기는 것을 전제하되 문장이 와도 동작한다.
--
-- ⚠ 한계 — 어휘검색 1위 정확도 6/10 (2026-10-05, 10질의 실측).
--    법이 그 단어를 쓰지 않는 질의는 후보에도 못 들어온다. 예: 「주휴수당」은 법에 없고
--    「유급휴일」이다. 「임금체불 벌칙」의 제107조는 제목이 「벌칙」이고 본문이
--    제36조·제43조를 번호로만 인용한다. **근본 해결은 조문 임베딩**이고 별건이다.
DROP FUNCTION IF EXISTS public.search_law_articles(text, integer, text);

CREATE FUNCTION public.search_law_articles(
  query_text text,
  max_results integer DEFAULT 6,
  law_hint text DEFAULT NULL
)
RETURNS TABLE(
  law_name text, article_label text, article_title text, body text,
  law_kind text, effective_date date, score double precision, matched int
)
LANGUAGE sql STABLE AS $function$
  WITH toks AS (
    -- 2글자 이상만. 1글자는 변별력이 없고 trgm·ILIKE 에서 전수스캔을 만든다
    SELECT DISTINCT t FROM unnest(
      regexp_split_to_array(regexp_replace(trim(query_text), '\s+', ' ', 'g'), ' ')
    ) AS t WHERE length(t) >= 2
  ), cand AS (
    SELECT a.law_name, a.article_label, a.article_title, a.body,
           a.law_kind, a.effective_date,
           sum(
             -- 제목 일치가 가장 강하다. 조문 제목은 짧고 주제가 분명하다
             CASE WHEN a.article_title ILIKE '%' || k.t || '%' THEN 4 ELSE 0 END
             -- 본문은 길어서 약하게 본다
           + CASE WHEN a.body ILIKE '%' || k.t || '%' THEN 1 ELSE 0 END
           )::float
           + CASE a.law_kind WHEN '법률' THEN 0.6 ELSE 0 END   -- 법률 > 시행령 > 시행규칙
           + CASE WHEN law_hint IS NOT NULL AND a.law_name = law_hint THEN 3 ELSE 0 END
           + coalesce(max(similarity(a.article_title, query_text)) * 4, 0) AS score,
           count(*) FILTER (
             WHERE a.article_title ILIKE '%' || k.t || '%'
                OR a.body ILIKE '%' || k.t || '%')::int AS matched
    FROM law_articles a CROSS JOIN toks k
    WHERE NOT a.is_heading AND NOT a.is_byeolpyo AND NOT a.is_deleted
      AND a.body IS NOT NULL
      AND (a.article_title ILIKE '%' || k.t || '%' OR a.body ILIKE '%' || k.t || '%')
    GROUP BY a.law_name, a.article_label, a.article_title, a.body,
             a.law_kind, a.effective_date
  )
  SELECT law_name, article_label, article_title, body, law_kind,
         effective_date, score, matched
  FROM cand
  ORDER BY matched DESC, score DESC, length(body) ASC
  LIMIT max_results;
$function$;
